apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-demo"
  namespace: "clickhouse"
spec:
  defaults:
    templates:
      serviceTemplate: chi-service-template
  configuration:
    users:
      default/networks/ip: 
        - "::/0"
        - "0.0.0.0"
        - "127.0.0.1"
    # settings:
    #   mysql_port: 3306
      # http_port: 8123
      # tcp_port: 9000
      # interserver_http_port: 9009
    zookeeper:
      nodes:
      - host: zookeeper.zoo1ns
        port: 2181
    clusters:
      - name: "ck-demo"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          # serviceTemplate: chi-service-template
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: ch-endpoint-{chi}
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: NodePort
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:21.3.20.2.altinitystable
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: local
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

